# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-08-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
